In [1]:
! pip install nltk

Requirement already satisfied: nltk in /opt/miniconda3/lib/python3.12/site-packages (3.9.1)
Requirement already satisfied: click in /opt/miniconda3/lib/python3.12/site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /opt/miniconda3/lib/python3.12/site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /opt/miniconda3/lib/python3.12/site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in /opt/miniconda3/lib/python3.12/site-packages (from nltk) (4.66.5)

Import the data

Link to data - https://www.kaggle.com/datasets/mdismielhossenabir/sentiment-analysis/data

In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv('sentiment_analysis.csv')

In [4]:
df

,Year,Month,Day,Time of Tweet,text,sentiment,Platform
0,2018,8,18,morning,What a great day!!! Looks like dream.,positive,Twitter
1,2018,8,18,noon,"I feel sorry, I miss you here in the sea beach",positive,Facebook
2,2017,8,18,night,Don't angry me,negative,Facebook
3,2022,6,8,morning,We attend in the class just for listening teac...,negative,Facebook
4,2022,6,8,noon,"Those who want to go, let them go",negative,Instagram
...,...,...,...,...,...,...,...
494,2015,10,18,night,"According to , a quarter of families under six...",negative,Twitter
495,2021,2,25,morning,the plan to not spend money is not going well,negative,Instagram
496,2022,5,30,noon,uploading all my bamboozle pictures of facebook,neutral,Facebook
497,2018,8,10,night,congratulations ! you guys finish a month ear...,positive,Twitter
498,2019,3,25,morning,"actually, I wish I was back in Tahoe. I miss...",negative,Instagram

In [5]:
df['sentiment'].unique()

array(['positive', 'negative', 'neutral'], dtype=object)

In [6]:
df['sentiment'].value_counts()

sentiment
neutral     199
positive    166
negative    134
Name: count, dtype: int64

In [7]:
df = df[['text','sentiment']]

In [8]:
df

                                                  text sentiment
0                What a great day!!! Looks like dream.  positive
1       I feel sorry, I miss you here in the sea beach  positive
2                                       Don't angry me  negative
3    We attend in the class just for listening teac...  negative
4                    Those who want to go, let them go  negative
..                                                 ...       ...
494  According to , a quarter of families under six...  negative
495      the plan to not spend money is not going well  negative
496    uploading all my bamboozle pictures of facebook   neutral
497   congratulations ! you guys finish a month ear...  positive
498   actually, I wish I was back in Tahoe.  I miss...  negative

[499 rows x 2 columns]

using Vader and SIA

In [10]:
pip install datasets

Collecting datasets
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: filelock in /opt/miniconda3/lib/python3.12/site-packages (from datasets) (3.16.1)
Requirement already satisfied: numpy>=1.17 in /opt/miniconda3/lib/python3.12/site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /opt/miniconda3/lib/python3.12/site-packages (from datasets) (18.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.12/site-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /opt/miniconda3/lib/python3.12/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /opt/miniconda3/lib/python3.12/site-packages (from datasets) (4.66.5)
Collecting xxhash (from datasets)
  Using cached xxhash-3.5.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Using cached multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Collecting aiohttp (from datasets)
  Downloading aiohttp-3.11.11-cp312-cp312-macosx_11_0_arm64.whl.metadata (7.7 kB)
Requirement already satisfied: huggingface-hub>=0.23.0 in /opt/miniconda3/lib/python3.12/site-packages (from datasets) (0.26.2)
Requirement already satisfied: packaging in /opt/miniconda3/lib/python3.12/site-packages (from datasets) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /opt/miniconda3/lib/python3.12/site-packages (from datasets) (6.0.2)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->datasets)
  Downloading aiohappyeyeballs-2.4.4-py3-none-any.whl.metadata (6.1 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->datasets)
  Downloading aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: attrs>=17.3.0 in /opt/miniconda3/lib/python3.12/site-packages (from aiohttp->datasets) (24.2.0)
Collecting frozenlist>=1.1.1 (from aiohttp->datasets)
  Downloading frozenlist-1.5.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->datasets)
  Downloading multidict-6.1.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (5.0 kB)
Collecting propcache>=0.2.0 (from aiohttp->datasets)
  Downloading propcache-0.2.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (9.2 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp->datasets)
  Downloading yarl-1.18.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (69 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/miniconda3/lib/python3.12/site-packages (from huggingface-hub>=0.23.0->datasets) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/miniconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/miniconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda3/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2024.8.30)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.12/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/miniconda3/lib/python3.12/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniconda3/lib/python3.12/site-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
Downloading aiohttp-3.11.11-cp312-cp312-macosx_11_0_arm64.whl (455 kB)
Using cached multiprocess-0.70.16-py312-none-any.whl (146 kB)
Using cached xxhash-3.5.0-cp312-cp312-macosx_11_0_arm64.whl (30 kB)
Downloading aiohappyeyeballs-2.4.4-py3-none-any.whl (14 kB)
Downloading aiosignal-1.3.2-py2.py3-none-any.whl (7.6 kB)
Downloading frozenlist-1.5.0-cp312-cp312-macosx_11_0_arm64.whl (51 kB)
Downloading multidict-6.1.0-cp312-cp312-macosx_11_0_arm64.whl (29 kB)
Downloading propcache-0.2.1-cp312-cp312-macosx_11_0_arm64.whl (45 kB)
Downloading yarl-1.18.3-cp312-cp312-macosx_11_0_arm64.whl (92 kB)
Installing collected packages: xxhash, propcache, multidict, fsspec, frozenlist, dill, aiohappyeyeballs, yarl, multiprocess, aiosignal, aiohttp, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
Successfully installed aiohappyeyeballs-2.4.4 aiohttp-3.11.11 aiosignal-1.3.2 datasets-3.2.0 dill-0.3.8 frozenlist-1.5.0 fsspec-2024.9.0 multidict-6.1.0 multiprocess-0.70.16 propcache-0.2.1 xxhash-3.5.0 yarl-1.18.3
Note: you may need to restart the kernel to use updated packages.

In [11]:
import nltk
from datasets import load_dataset
from nltk.sentiment import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()

In [12]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/varikuntlasaimanoj/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

Understanding SIA

In [13]:
sentence = "This movie was amazing, but the acting was a bit disappointing."
sentiment_scores = sia.polarity_scores(sentence)
print(sentiment_scores)

{'neg': 0.293, 'neu': 0.544, 'pos': 0.163, 'compound': -0.4404}

In [14]:
def analyze_sentiment_nltk(review):
    score = sia.polarity_scores(review)
    final_score = score['compound']
    if final_score > 0.4:
        return 'positive'
    elif final_score >= -0.3 and final_score <= 0.4:
        return 'neutral'
    else :
        return 'negative'

In [15]:
df['predicted_sentiment_nltk'] = df['text'].apply(analyze_sentiment_nltk)

/var/folders/wx/hplkvjgn51g_g50mtj_1xhzr0000gn/T/ipykernel_1328/3535986600.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['predicted_sentiment_nltk'] = df['text'].apply(analyze_sentiment_nltk)

In [16]:
df

,text,sentiment,predicted_sentiment_nltk
0,What a great day!!! Looks like dream.,positive,positive
1,"I feel sorry, I miss you here in the sea beach",positive,neutral
2,Don't angry me,negative,positive
3,We attend in the class just for listening teac...,negative,neutral
4,"Those who want to go, let them go",negative,neutral
...,...,...,...
494,"According to , a quarter of families under six...",negative,negative
495,the plan to not spend money is not going well,negative,neutral
496,uploading all my bamboozle pictures of facebook,neutral,negative
497,congratulations ! you guys finish a month ear...,positive,positive
498,"actually, I wish I was back in Tahoe. I miss...",negative,neutral

In [17]:
df['prediction_correctness_nltk'] = np.where(df['sentiment']==df['predicted_sentiment_nltk'],1,0)

/var/folders/wx/hplkvjgn51g_g50mtj_1xhzr0000gn/T/ipykernel_1328/1528029338.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['prediction_correctness_nltk'] = np.where(df['sentiment']==df['predicted_sentiment_nltk'],1,0)

In [18]:
df

,text,sentiment,predicted_sentiment_nltk,prediction_correctness_nltk
0,What a great day!!! Looks like dream.,positive,positive,1
1,"I feel sorry, I miss you here in the sea beach",positive,neutral,0
2,Don't angry me,negative,positive,0
3,We attend in the class just for listening teac...,negative,neutral,0
4,"Those who want to go, let them go",negative,neutral,0
...,...,...,...,...
494,"According to , a quarter of families under six...",negative,negative,1
495,the plan to not spend money is not going well,negative,neutral,0
496,uploading all my bamboozle pictures of facebook,neutral,negative,0
497,congratulations ! you guys finish a month ear...,positive,positive,1
498,"actually, I wish I was back in Tahoe. I miss...",negative,neutral,0

In [19]:
df['prediction_correctness_nltk'].value_counts()

prediction_correctness_nltk
1    323
0    176
Name: count, dtype: int64

In [20]:
df

,text,sentiment,predicted_sentiment_nltk,prediction_correctness_nltk
0,What a great day!!! Looks like dream.,positive,positive,1
1,"I feel sorry, I miss you here in the sea beach",positive,neutral,0
2,Don't angry me,negative,positive,0
3,We attend in the class just for listening teac...,negative,neutral,0
4,"Those who want to go, let them go",negative,neutral,0
...,...,...,...,...
494,"According to , a quarter of families under six...",negative,negative,1
495,the plan to not spend money is not going well,negative,neutral,0
496,uploading all my bamboozle pictures of facebook,neutral,negative,0
497,congratulations ! you guys finish a month ear...,positive,positive,1
498,"actually, I wish I was back in Tahoe. I miss...",negative,neutral,0

Using textblob

In [21]:
! pip install textblob

Requirement already satisfied: textblob in /opt/miniconda3/lib/python3.12/site-packages (0.18.0.post0)
Requirement already satisfied: nltk>=3.8 in /opt/miniconda3/lib/python3.12/site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /opt/miniconda3/lib/python3.12/site-packages (from nltk>=3.8->textblob) (8.1.7)
Requirement already satisfied: joblib in /opt/miniconda3/lib/python3.12/site-packages (from nltk>=3.8->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /opt/miniconda3/lib/python3.12/site-packages (from nltk>=3.8->textblob) (2024.9.11)
Requirement already satisfied: tqdm in /opt/miniconda3/lib/python3.12/site-packages (from nltk>=3.8->textblob) (4.66.5)

In [22]:
from textblob import TextBlob

In [23]:
def analyze_sentiment_textblob(review):
    blob = TextBlob(review)
    if blob.sentiment.polarity >= 0.4:
        return 'positive'
    elif blob.sentiment.polarity >= -0.3 and blob.sentiment.polarity <= 0.4:
        return 'neutral'
    else : 
        return 'negative'

In [24]:
analyze_sentiment_textblob('This is a good movie')

'positive'

In [25]:
df['predicted_sentiment_textblob'] = df['text'].apply(analyze_sentiment_textblob)

/var/folders/wx/hplkvjgn51g_g50mtj_1xhzr0000gn/T/ipykernel_1328/3547837887.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['predicted_sentiment_textblob'] = df['text'].apply(analyze_sentiment_textblob)

In [26]:
df

,text,sentiment,predicted_sentiment_nltk,prediction_correctness_nltk,predicted_sentiment_textblob
0,What a great day!!! Looks like dream.,positive,positive,1,positive
1,"I feel sorry, I miss you here in the sea beach",positive,neutral,0,negative
2,Don't angry me,negative,positive,0,negative
3,We attend in the class just for listening teac...,negative,neutral,0,neutral
4,"Those who want to go, let them go",negative,neutral,0,neutral
...,...,...,...,...,...
494,"According to , a quarter of families under six...",negative,negative,1,neutral
495,the plan to not spend money is not going well,negative,neutral,0,neutral
496,uploading all my bamboozle pictures of facebook,neutral,negative,0,neutral
497,congratulations ! you guys finish a month ear...,positive,positive,1,neutral
498,"actually, I wish I was back in Tahoe. I miss...",negative,neutral,0,neutral

In [27]:
df['prediction_correctness_textblob'] = np.where(df['sentiment']==df['predicted_sentiment_textblob'],1,0)

/var/folders/wx/hplkvjgn51g_g50mtj_1xhzr0000gn/T/ipykernel_1328/4004997036.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['prediction_correctness_textblob'] = np.where(df['sentiment']==df['predicted_sentiment_textblob'],1,0)

In [28]:
df

,text,sentiment,predicted_sentiment_nltk,prediction_correctness_nltk,predicted_sentiment_textblob,prediction_correctness_textblob
0,What a great day!!! Looks like dream.,positive,positive,1,positive,1
1,"I feel sorry, I miss you here in the sea beach",positive,neutral,0,negative,0
2,Don't angry me,negative,positive,0,negative,1
3,We attend in the class just for listening teac...,negative,neutral,0,neutral,0
4,"Those who want to go, let them go",negative,neutral,0,neutral,0
...,...,...,...,...,...,...
494,"According to , a quarter of families under six...",negative,negative,1,neutral,0
495,the plan to not spend money is not going well,negative,neutral,0,neutral,0
496,uploading all my bamboozle pictures of facebook,neutral,negative,0,neutral,1
497,congratulations ! you guys finish a month ear...,positive,positive,1,neutral,0
498,"actually, I wish I was back in Tahoe. I miss...",negative,neutral,0,neutral,0

In [29]:
df['prediction_correctness_textblob'].value_counts()

prediction_correctness_textblob
1    282
0    217
Name: count, dtype: int64

In [30]:
df

,text,sentiment,predicted_sentiment_nltk,prediction_correctness_nltk,predicted_sentiment_textblob,prediction_correctness_textblob
0,What a great day!!! Looks like dream.,positive,positive,1,positive,1
1,"I feel sorry, I miss you here in the sea beach",positive,neutral,0,negative,0
2,Don't angry me,negative,positive,0,negative,1
3,We attend in the class just for listening teac...,negative,neutral,0,neutral,0
4,"Those who want to go, let them go",negative,neutral,0,neutral,0
...,...,...,...,...,...,...
494,"According to , a quarter of families under six...",negative,negative,1,neutral,0
495,the plan to not spend money is not going well,negative,neutral,0,neutral,0
496,uploading all my bamboozle pictures of facebook,neutral,negative,0,neutral,1
497,congratulations ! you guys finish a month ear...,positive,positive,1,neutral,0
498,"actually, I wish I was back in Tahoe. I miss...",negative,neutral,0,neutral,0